### ISSUE TITLE
4.17 Build with new features?

### ISSUE THREAD

**Issue by Derjyn** [jinyuliao/GenericGraph#3]
I've been trying to merge in some of the changes, back to the last version that was compatible with 4.17, and am running into issues.  Are you no longer supporting 4.17?

**Comment by jinyuliao** [comment]
I've pushed a branch: [4.17](https://github.com/jinyuliao/GenericGraph/tree/4.17), bring new features to UE 4.17, you can check it out.

**Comment by Derjyn** [comment]
Thanks for that.  Though cleaning up my project, adding that new version, then generating VS project files and trying to compile yields no results.  It's as if the plugin doesn't exist.  It's in the VS solution/project, but nothing compiles for it.  I repeated the process for other plugins, and they worked fine.  I repeated it for an older version of GenericGraph, and it worked fine.

**Comment by Derjyn** [comment]
Correction to my last statement:  I just realized I downloaded the base of that 4.17 branch.  I grabbed the version with the [latest commit](https://github.com/jinyuliao/GenericGraph/tree/3d56709d8aca3bcac66b52bf28c751c5943e8494), and it compiles now.  Thanks, and I'm marking this as solved!

**Comment by Derjyn** [comment]
I spoke too soon- shipping build won't compile:

`GenericGraphRuntime\Private\GenericGraph.cpp(45): error C2065: 'GEngine': undeclared identifier`
AND
```
GenericGraphRuntime\GenericGraphNode.gen.cpp(214): error C2039: 'ContextMenuName': is not a member of 'UGenericGraphNode'
GenericGraphRuntime\GenericGraphNode.gen.cpp(214): error C2664: 'UTextProperty::UTextProperty(const UTextProperty &)': cannot convert argument 1 from 'FObjectInitializer' to 'ECppProperty'
GenericGraphRuntime\GenericGraphNode.gen.cpp(215): error C2039: 'BackgroundColor': is not a member of 'UGenericGraphNode'
GenericGraphRuntime\GenericGraphNode.gen.cpp(215): error C2664: 'UStructProperty::UStructProperty(const UStructProperty &)': cannot convert argument 1 from 'FObjectInitializer' to 'ECppProperty'
GenericGraphRuntime\GenericGraphNode.gen.cpp(216): error C2039: 'CompatibleGraphType': is not a member of 'UGenericGraphNode'
GenericGraphRuntime\GenericGraphNode.gen.cpp(216): error C2664: 'UClassProperty::UClassProperty(const UClassProperty &)': cannot convert argument 1 from 'FObjectInitializer' to 'ECppProperty'
```
I fixed the first issue by commenting out the GEngine block in GenericGraph.cpp:
```
//if (ToScreen && GEngine != nullptr)
//{
//    GEngine->AddOnScreenDebugMessage(-1, 15.f, FColor::Blue, Message);
//}
```

The generated issues are still there, though.  Any help is much appreciated!

**Comment by jinyuliao** [comment]
I've pushed a fix on master and 4.17 branch, you update and can try again.

**Comment by Derjyn** [comment]
Awesome, thanks.  Almost there- compiled for both Development Editor and Shipping builds without issue.  However, creating a new generic graph asset has some issues.  Firstly, the details panel has "unrecognized tab", with no options accessible.  Second, the "Generic Graph Settings" window appears to have some non-agnostic sample material left in there.  Not sure if this is by design or not, or how many versions that has been present.  See the attached screenshots.

Thanks for being so quick and attentive, much appreciated.  I'll keep testing over the next couple of days while I'm working on other elements of my project.  This is a handy asset to have in the toolbelt, I'm surprised it hasn't gotten more attention!

![capture](https://user-images.githubusercontent.com/648059/33927755-4c9b9cec-df98-11e7-8830-c2cbaf582839.PNG)
![capture2](https://user-images.githubusercontent.com/648059/33927756-4cb0c9fa-df98-11e7-8d84-6f3c99bd6e3c.PNG)

**Comment by jinyuliao** [comment]
* “unrecognized tab” caused by a rename of the panel, you can just close it and click the "Window->property" to open the new property window.
* "Generic Graph Settings" has some parameters to adjust “auto arrange”'s behavior, the name come form , most of the time, you don't need change the settings, especially the advance setting.
* From your screenshots, the AutoArrange's icon seems has some problem, the icon file 's path is ${Plugins}/GenericGraph/Resources/AutoArrangeIcon.png
Finally, your asset editor should looks like this:
![image](https://user-images.githubusercontent.com/2009308/33928455-f1b26458-e020-11e7-98dc-7a7f3d8ece31.png)

**Comment by Derjyn** [comment]
Perfect, thanks for clearing those issues up.  Shortly after posting, I pondered about the names of those items in the graph settings, and the thought crossed my mind that they might actually be related to the auto-arrange.  Interesting!

I double checked the location of the auto-arrange icon, and it's in it's proper place.  I recompiled the plugin, making sure it was in the correct directory, but it still shows up white.  Before you pointed that out, I actually thought it was an issue with Slate rendering having an attitude...  I have a screenshot to verify that it's in the proper place.

![capture](https://user-images.githubusercontent.com/648059/33929236-9ec9b616-df9d-11e7-94bb-c40f93f2d412.PNG)

**Comment by Derjyn** [comment]
Okay, I did a more in-depth project cleanup and rebuilt the plugin again, as well as reset all my customized settings.  The icon shows up correctly now.  Outside of more in-depth testing, so far everything seems to be operating as it should!

Marking this as closed again.  Thanks for all the assistance.  Hopefully I won't be back with more issues 👶
